module.exports={
    'recycled wool': 'recycled_wool',
    'recycled cashmere': 'recycled_cashmere',
    'regenerated cashmere': 'recycled_cashmere',
    'recycled polyester': 'recycled_polyester',
    'recycled pet': 'recycled_polyester',
    'rpet': 'recycled_polyester',
    'pet newlife': 'recycled_polyester',
    'post-consumption bottles': 'recycled_polyester',
    'linen': 'linen',
    'organic linen': 'linen',
    'hemp': 'hemp',
    'organic hemp': 'hemp',
    'vegan leather': 'vegan_leather',
    'natural leather': 'vegan_leather',
    'vegan nappa': 'vegan_leather',
    'eco vegan suede nappa': 'vegan_leather',
    'vegan eco-nappa': 'vegan_leather',
    'soft vegan micronappa': 'vegan_leather',
    'vegan grain leather': 'vegan_leather',
    'eco-nappa': 'vegan_leather',
    'eco alter vegan nappa': 'vegan_leather',
    'vegan suede': 'vegan_leather',
    'upcycled microsuede': 'vegan_leather',
    'soft vegan suede': 'vegan_leather',
    'vegan micro suede': 'vegan_leather',
    'life nappa': 'vegan_leather',
    'silicone with faux leather trim': 'vegan_leather',
    'vegan patent leather': 'vegan_leather',
    'eco-certified leather': 'vegan_leather',
    'organic cotton': 'organic_cotton',
    'organic certified cotton': 'organic_cotton',
    'organic fairtrade certified cotton': 'organic_cotton',
    '100% organic undyed cotton': 'organic_cotton',
    'organic denim': 'organic_cotton',
    'cotton (organic)': 'organic_cotton',
    'certified organic cotton': 'organic_cotton',
    'recycled cotton': 'recycled_cotton',
    'recycled jeans cotton': 'recycled_cotton',
}